In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xb

In [4]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000,n_features=4,n_informative=2,shuffle =False,n_redundant=0,random_state=0)

In [5]:
ab = AdaBoostClassifier()
gb = GradientBoostingClassifier()
x = xb.XGBClassifier()

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33,random_state=42)

In [7]:
ab.fit(X_train,y_train)
y_pred = ab.predict(X_test)

In [8]:
from sklearn.metrics import *
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.9242424242424242
              precision    recall  f1-score   support

           0       0.92      0.93      0.92       165
           1       0.93      0.92      0.92       165

    accuracy                           0.92       330
   macro avg       0.92      0.92      0.92       330
weighted avg       0.92      0.92      0.92       330

[[153  12]
 [ 13 152]]


In [10]:
gb.fit(X_train,y_train)
y_pred = gb.predict(X_test)
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.9393939393939394
              precision    recall  f1-score   support

           0       0.92      0.96      0.94       160
           1       0.96      0.92      0.94       170

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330

[[153   7]
 [ 13 157]]


In [11]:
x.fit(X_train,y_train)
y_pred = x.predict(X_test)
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.9393939393939394
              precision    recall  f1-score   support

           0       0.93      0.95      0.94       164
           1       0.95      0.93      0.94       166

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330

[[155   9]
 [ 11 155]]
