In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

In [3]:
from sklearn import datasets
df = datasets.load_iris()

In [6]:
X=df.data
y = df.target

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X=scaler.fit_transform(X)

In [13]:
X[1]

array([-1.14301691, -0.13197948, -1.34022653, -1.3154443 ])

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.33)

In [17]:
pca =PCA(n_components=3)
X_train = pca.fit_transform(X_train)
X_train

array([[ 1.67505415e-01,  2.86881206e-01,  1.33096812e-01],
       [ 2.75613761e+00, -7.60177303e-01, -5.89819468e-01],
       [ 3.00157318e-01,  1.08561191e-01,  4.69287274e-01],
       [-2.27200428e+00, -7.20325740e-01, -1.44958785e-01],
       [ 2.88042301e+00, -3.68492288e-01, -8.68642615e-01],
       [ 7.68989701e-02,  6.84855446e-01, -3.29734500e-01],
       [-2.15653978e+00, -5.47876996e-01, -2.89353931e-01],
       [-2.29665431e+00, -6.81499254e-01,  1.78679208e-02],
       [-2.10689179e+00, -1.37112835e+00,  2.36405494e-01],
       [-2.98899166e-01,  2.53159402e+00, -9.12695500e-02],
       [ 1.26470040e+00,  4.45663511e-01, -2.56864642e-02],
       [-2.25300422e+00, -3.74559198e-01,  9.51695228e-02],
       [-2.02211355e+00,  3.99595927e-01, -3.32978662e-01],
       [-1.85003116e+00, -2.99248077e-01,  1.50570212e-02],
       [ 2.01493964e-01,  7.60199713e-01,  1.03497296e-01],
       [-2.18896203e+00, -5.04652035e-01, -1.95169855e-01],
       [ 4.34663786e-02,  7.51880225e-02

In [18]:
X_test=pca.transform(X_test)

In [19]:
X_test

array([[ 5.71811831e-01,  3.36561268e-01, -3.15770286e-01],
       [-1.85368138e+00, -1.62524373e+00, -3.81767289e-01],
       [ 3.26917156e+00,  5.21674199e-02, -7.16413960e-01],
       [ 6.12562263e-01,  1.52588915e-01,  6.57013535e-02],
       [ 1.21300681e+00,  3.02050416e-02, -7.44327746e-01],
       [-1.84357888e+00, -6.40198189e-01, -2.85926766e-01],
       [-9.74887897e-02,  3.27180486e-01,  1.72770833e-01],
       [ 1.89686646e+00, -6.89178456e-01,  1.24583829e-01],
       [ 1.09257967e+00,  1.57376515e+00, -5.13080041e-01],
       [ 1.58892548e-01,  6.76894403e-01, -1.76874938e-01],
       [ 1.36179745e+00, -7.22518478e-01,  2.75518954e-01],
       [-2.29407767e+00,  4.87936598e-01, -2.59976045e-01],
       [-2.04264158e+00, -8.91971721e-01, -4.98333636e-01],
       [-2.24502397e+00,  2.30291796e-01, -2.80587599e-01],
       [-2.31401141e+00, -1.36923760e+00,  1.21039959e-01],
       [ 7.50902463e-01, -8.39581764e-01,  1.38294695e-01],
       [ 1.84244748e+00, -2.96206431e-01

In [20]:
pca.explained_variance_ratio_

array([0.71833367, 0.23248308, 0.04401235])

In [21]:
0.71833367+0.23248308+0.04401235

0.9948291

In [22]:
pca.components_

array([[ 1.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00],
       [-0.00000000e+00,  1.00000000e+00, -1.85409114e-16,
        -1.91114293e-17],
       [-0.00000000e+00,  1.54546397e-16,  1.00000000e+00,
        -2.24365434e-16]])